import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faGithub,
  faProductHunt,
  faSoundcloud,
} from '@fortawesome/free-brands-svg-icons'
import {
  faAlignJustify,
  faArrowCircleUp,
  faBars,
  faBinoculars,
  faBold,
  faBook,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faCircle,
  faCode,
  faColumns,
  faComment,
  faEdit,
  faEllipsisH,
  faEnvelope,
  faExternalLinkAlt,
  faEyeDropper,
  faFile,
  faFolder,
  faGripLinesVertical,
  faImage,
  faInfoCircle,
  faItalic,
  faLink,
  faList,
  faListOl,
  faLock,
  faMinus,
  faMoon,
  faPen,
  faPenSquare,
  faPlusCircle,
  faQuoteRight,
  faRocket,
  faSignOutAlt,
  faSpinner,
  faSync,
  faTable,
  faTimes,
  faTrash,
  faUnlock,
  faUser,
} from '@fortawesome/free-solid-svg-icons'
import React, { ReactNode } from 'react'

library.add(
  faGithub,
  faSoundcloud,
  faEnvelope,
  faUser,
  faMoon,
  faComment,
  faPenSquare,
  faBook,
  faPlusCircle,
  faSync,
  faTrash,
  faTimes,
  faExternalLinkAlt,
  faChevronRight,
  faChevronDown,
  faEllipsisH,
  faGripLinesVertical,
  faProductHunt,
  faEdit,
  faPen,
  faImage,
  faSignOutAlt,
  faFile,
  faFolder,
  faSpinner,
  faEyeDropper,
  faListOl,
  faCode,
  faList,
  faItalic,
  faBold,
  faMinus,
  faQuoteRight,
  faColumns,
  faLink,
  faTable,
  faBars,
  faAlignJustify,
  faBinoculars,
  faRocket,
  faInfoCircle,
  faCircle,
  faCheckCircle,
  faArrowCircleUp,
  faCheck,
  faLock,
  faUnlock
)

interface IIconProvider {
  children?: ReactNode
}

export function IconProvider({ children }: IIconProvider) {
  return <>{children}</>
}
