version: 2
jobs:
  build:
    working_directory: ~/noted
    docker:
      - image: circleci/node:erbium
    environment:
      BUCKET: noted
      REGION: us-east-1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5a:9d:8b:79:ee:c3:d8:ed:5f:8f:72:80:b4:50:3a:40"
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install local dependencies
          command: yarn
      - run:
          name: Building
          command: yarn build
      - run:
          name: Install pip
          command: sudo apt-get install python-dev python-pip
      - run:
          name: Install aws cli
          command: sudo pip install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                echo "aws --region ${REGION} s3 sync build s3://${BUCKET}-staging/ --delete"
                aws --region ${REGION} s3 sync build s3://${BUCKET}-staging/ --delete
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "aws --region ${REGION} s3 sync build s3://${BUCKET}-master/ --delete"
                aws --region ${REGION} s3 sync build s3://${BUCKET}-master/ --delete
            fi