version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:erbium

commands:
  install-dependencies:
    description: 'Install node module dependencies'
    steps:
      - run: yarn install --frozen-lockfile
  cache-dependencies:
    description: 'Cache the node_modules'
    steps:
      - save_cache:
          key: v4-node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  restore-cached-dependencies:
    description: 'Restore node modules from the cache'
    steps:
      - restore_cache:
          keys:
            - v4-node_modules-{{ checksum "yarn.lock" }}
  run-unit-tests:
    description: 'Run unit tests'
    steps:
      - run: yarn test --ci --runInBand
  run-linter-check:
    description: 'Run linter'
    steps:
      - run: yarn lint
  run-typescript-check:
    description: 'Run typescript tests'
    steps:
      - run: yarn ts
  configure-aws:
    description: 'Install dependencies for AWS and Serverless'
    steps:
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli
  persist-to-workspace:
    description: 'Persist the dist file to the workspace'
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
  attach-to-workspace:
    description: 'Attach the dist file to the workspace'
    steps:
      - attach_workspace:
          at: ~/

jobs:
  prepare:
    executor: nodejs
    steps:
      - checkout
      - restore-cached-dependencies
      - install-dependencies
      - cache-dependencies
  test:
    executor: nodejs
    steps:
      - checkout
      - restore-cached-dependencies
      - run-unit-tests
  eslint:
    executor: nodejs
    steps:
      - checkout
      - restore-cached-dependencies
      - run-linter-check
  typescript:
    executor: nodejs
    steps:
      - checkout
      - restore-cached-dependencies
      - run-typescript-check
  build:
    parameters:
      env:
        description: 'The name of the bucket to deploy to.'
        type: string
    executor: nodejs
    steps:
      - checkout
      - restore-cached-dependencies
      - run: export REACT_APP_NODE_ENV=<< parameters.env >> && . ./.circleci/build_env.sh && yarn build
      - persist-to-workspace
  deploy:
    parameters:
      bucket:
        description: 'The name of the environment to deploy to.'
        type: string
    executor: nodejs
    steps:
      - checkout
      - attach-to-workspace
      - configure-aws
      - run: aws configure set default.s3.signature_version s3v4
      - run: aws --region us-east-1 s3 sync build s3://<< parameters.bucket >>/ --delete

workflows:
  version: 2
  main:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - eslint:
          requires:
            - prepare
      - typescript:
          requires:
            - prepare

      - build:
          name: build-development
          env: development
          requires:
            - test
            - eslint
            - typescript
          filters:
            branches:
              only: master

      - deploy:
          name: deploy-development
          bucket: noted-development
          requires:
            - build-development

      - approve-production:
          type: approval
          requires:
            - deploy-development

      - build:
          name: build-production
          env: production
          requires:
            - approve-production

      - deploy:
          bucket: notehub.xyz
          requires:
            - build-production
